// src/pages/Landing.jsx
import { Link } from "react-router-dom"
import Navbar from "../components/Navbar"
import Footer from "../components/Footer"
import "../styles/landing.css"

function Landing() {
  return (
    <div className="landing-page">
      <Navbar />
      <main className="landing-main">
        {/* Hero Section */}
        <section className="hero-section">
          <svg className="wave-svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
            <path d="M0,50 Q300,0 600,50 T1200,50 L1200,120 L0,120 Z" fill="currentColor" />
          </svg>
          <div className="hero-content">
            <div className="decorative-circle"></div>
            <h1>emannx-tickets</h1>
            <p>Streamline your workflow with intelligent ticket management</p>
            <div className="hero-buttons">
              <Link to="/auth/login" className="btn btn-primary">
                Login
              </Link>
              <Link to="/auth/signup" className="btn btn-secondary">
                Get Started
              </Link>
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section className="features-section">
          <h2>Why Choose emannx-tickets?</h2>
          <div className="features-grid">
            <div className="feature-box">
              <h3>Easy Management</h3>
              <p>Create, update, and manage tickets with an intuitive interface.</p>
            </div>
            <div className="feature-box">
              <h3>Real-time Updates</h3>
              <p>Track ticket status and priority in real-time.</p>
            </div>
            <div className="feature-box">
              <h3>Secure & Reliable</h3>
              <p>Your data is safe with our secure authentication system.</p>
            </div>
            <div className="feature-box">
              <h3>Responsive Design</h3>
              <p>Access your tickets from any device, anytime, anywhere.</p>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  )
}

export default Landing

// src/pages/Landing.vue
<template>
  <div class="landing-page">
    <Navbar />
    <main class="landing-main">
      <!-- Hero Section -->
      <section class="hero-section">
        <svg class="wave-svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
          <path d="M0,50 Q300,0 600,50 T1200,50 L1200,120 L0,120 Z" fill="currentColor" />
        </svg>
        <div class="hero-content">
          <div class="decorative-circle"></div>
          <h1>emannx-tickets</h1>
          <p>Streamline your workflow with intelligent ticket management</p>
          <div class="hero-buttons">
            <router-link to="/auth/login" class="btn btn-primary">Login</router-link>
            <router-link to="/auth/signup" class="btn btn-secondary">Get Started</router-link>
          </div>
        </div>
      </section>

      <!-- Features Section -->
      <section class="features-section">
        <h2>Why Choose emannx-tickets?</h2>
        <div class="features-grid">
          <div class="feature-box">
            <h3>Easy Management</h3>
            <p>Create, update, and manage tickets with an intuitive interface.</p>
          </div>
          <div class="feature-box">
            <h3>Real-time Updates</h3>
            <p>Track ticket status and priority in real-time.</p>
          </div>
          <div class="feature-box">
            <h3>Secure & Reliable</h3>
            <p>Your data is safe with our secure authentication system.</p>
          </div>
          <div class="feature-box">
            <h3>Responsive Design</h3>
            <p>Access your tickets from any device, anytime, anywhere.</p>
          </div>
        </div>
      </section>
    </main>
    <Footer />
  </div>
</template>

<script setup>
import Navbar from '../components/Navbar.vue'
import Footer from '../components/Footer.vue'
</script>

<style scoped>
.landing-page {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
}

.landing-main {
  flex: 1;
}

.hero-section {
  position: relative;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  padding: 4rem 2rem;
  text-align: center;
  overflow: hidden;
}

.wave-svg {
  position: absolute;
  bottom: -1px;
  left: 0;
  width: 100%;
  height: 120px;
  color: white;
}

.hero-content {
  position: relative;
  z-index: 1;
  max-width: 1440px;
  margin: 0 auto;
  padding: 4rem 2rem;
}

.decorative-circle {
  position: absolute;
  width: 300px;
  height: 300px;
  background-color: rgba(255, 255, 255, 0.1);
  border-radius: 50%;
  top: -100px;
  right: -100px;
  z-index: 0;
}

.hero-content h1 {
  font-size: 3.5rem;
  margin-bottom: 1rem;
  position: relative;
  z-index: 2;
}

.hero-content p {
  font-size: 1.25rem;
  margin-bottom: 2rem;
  color: rgba(255, 255, 255, 0.9);
  position: relative;
  z-index: 2;
}

.hero-buttons {
  display: flex;
  gap: 1rem;
  justify-content: center;
  position: relative;
  z-index: 2;
  flex-wrap: wrap;
}

.features-section {
  max-width: 1440px;
  margin: 0 auto;
  padding: 4rem 2rem;
}

.features-section h2 {
  text-align: center;
  margin-bottom: 3rem;
  color: var(--neutral-dark);
}

.features-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 2rem;
}

.feature-box {
  background-color: white;
  padding: 2rem;
  border-radius: var(--border-radius);
  box-shadow: var(--box-shadow);
  transition: transform 0.3s ease, box-shadow 0.3s ease;
}

.feature-box:hover {
  transform: translateY(-5px);
  box-shadow: 0 10px 20px rgba(0, 0, 0, 0.15);
}

.feature-box h3 {
  color: var(--primary-color);
  margin-bottom: 1rem;
}

.feature-box p {
  color: #6b7280;
}

@media (max-width: 768px) {
  .hero-section {
    padding: 2rem 1rem;
  }

  .hero-content {
    padding: 2rem 1rem;
  }

  .hero-content h1 {
    font-size: 2rem;
  }

  .hero-content p {
    font-size: 1rem;
  }

  .hero-buttons {
    flex-direction: column;
  }

  .btn {
    width: 100%;
  }

  .decorative-circle {
    width: 200px;
    height: 200px;
    top: -50px;
    right: -50px;
  }

  .features-grid {
    grid-template-columns: 1fr;
  }
}
</style>
